version: '3.4'

services:
  api:
    build: ./api
    volumes:
      - ./api/:/app
    ports:
      - "8080:8080"
    command: cargo watch -x run

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8081:8081"
    stdin_open: true
    command: yarn start
