version: '3.4'

services:
  rocket:
    build:
      context: rocket/
    volumes:
      - ../web/:/app
    ports:
      - "8080:8080"

  client:
    build:
      context: client/
    volumes:
      - ../client:/app
    ports:
      - "8081:8081"
    stdin_open: true
